
CREATE TABLE `table_researchers` ( 
    `id`  INT UNSIGNED NOT NULL AUTO_INCREMENT,  
    `researcherID` CHAR(15),  
    `password` CHAR(20),  
    `name` VARCHAR(30),
    `nickname`	VARCHAR(15),      
    `age`  FLOAT,
    `gender` CHAR(3), 
    `position`  VARCHAR(20),  
    `affiliation`  VARCHAR(20), 
    `country`  VARCHAR(20),
    `contact` VARCHAR(100),
    `email`  VARCHAR(20),  
    `registration_date`  DATETIME,
    `category`	VARCHAR(50),
    `status` VARCHAR(10),
    `credit` INT,  
    `description`	VARCHAR(200),
    `information` VARCHAR(200),   
    PRIMARY KEY(id)
);


CREATE TABLE `table_projects` ( 
    `id`  INT unsigned NOT NULL AUTO_INCREMENT,  
    `researcherID` CHAR(15),  
    `projectID` CHAR(15), 
    `name`	VARCHAR(30),
    `registration_date`  DATETIME,
    `category`	VARCHAR(50),
    `status` VARCHAR(10),
    `credit` INT,  
    `description`	VARCHAR(200),
    `information` VARCHAR(200),
    `link` VARCHAR(100),
    PRIMARY KEY(id)
);


CREATE TABLE `table_participants` ( 
    `id`  INT unsigned NOT NULL AUTO_INCREMENT,  
    `participantID` CHAR(15),  
    `password` CHAR(20),   
    `registration_date`  DATETIME,    
    `name`	VARCHAR(30),
    `nickname`	VARCHAR(15),      
    `age`  FLOAT,
    `gender` CHAR(3), 
    `zipcode` CHAR(6), 
    `email`  VARCHAR(20),  
    `information` VARCHAR(1000),
    `consent_type`  TINYINT,
    `diagnosis`  VARCHAR(20),
    `subtype`  VARCHAR(20),
    PRIMARY KEY(id)
);
    
CREATE TABLE `table_tasks` ( 
    `id`  INT unsigned NOT NULL AUTO_INCREMENT,  
    `taskID` CHAR(15),  
    `name`	CHAR(30),   
    `creator`	CHAR(20),   
    `registration_date`  DATETIME,
    `category`	VARCHAR(50),
    `status` VARCHAR(10),
    `credit` INT,  
    `description`	VARCHAR(200),
    `information` VARCHAR(200),
    `link` VARCHAR(100),
    `reference` VARCHAR(100),
    `conditions`	VARCHAR(50),     
    `stimulation_type`	VARCHAR(10), 
    `stimulation_choices`	VARCHAR(50), 
    `stimulus_duration`  SMALLINT unsigned, 
    `total_duration`	SMALLINT unsigned, 
    `post_trial_gap`	SMALLINT, 
    `poststimulus`  VARCHAR(20),
    `fixation_duration`  SMALLINT,  
    `stim_param_descript`	VARCHAR(30),      
    `sequence_length`   SMALLINT unsigned,  
    `response_ends_trial`   BOOLEAN,   
    `wait_duration_after_multiresponses` SMALLINT unsigned,
    `max_response_count`    TINYINT unsigned,
    `button_stimulus_mode`  BOOLEAN,  
    `adaptivemode`	TINYINT,      
    `default_param` JSON,
    PRIMARY KEY(id)
);

CREATE TABLE `table_task_sessions` ( 
    `id`   INT unsigned NOT NULL AUTO_INCREMENT,  
    `researcherID` CHAR(15),  
    `projectID` CHAR(15),  
    `participantID` CHAR(15),     
    `taskID`	CHAR(15), 
    `taskname`	CHAR(15),      
    `session`	TINYINT,  
    `phase`	    CHAR(10),
    `start_time`     DATETIME, 
    `total_time`	INT unsigned, 
    `score`	FLOAT,   
    `result`	VARCHAR(500),   
    `pretest_scores`	VARCHAR(50),        
    `total_score`	FLOAT,    
    `total_count` SMALLINT unsigned,  
    `total_rt_mean` FLOAT,
    `total_rt_sd` FLOAT,
    `total_unresponded_count`  SMALLINT unsigned,
    `target_count` SMALLINT unsigned,
    `target_rt_mean` FLOAT,
    `target_rt_sd` FLOAT,
    `target_unresponded_count`  SMALLINT unsigned,
    `target_correct_count` SMALLINT unsigned,
    `target_correct_rt_mean` FLOAT,
    `target_correct_rt_sd` FLOAT,
    `target_incorrect_count` SMALLINT unsigned,
    `target_incorrect_rt_mean` FLOAT,
    `target_incorrect_rt_sd` FLOAT,
    `nontarget_count` SMALLINT unsigned,
    `nontarget_rt_mean` FLOAT,
    `nontarget_rt_sd` FLOAT,
    `nontarget_unresponded_count`  SMALLINT unsigned,
    `nontarget_correct_count` SMALLINT unsigned,
    `nontarget_correct_rt_mean` FLOAT,
    `nontarget_correct_rt_sd` FLOAT,
    `nontarget_incorrect_count` SMALLINT unsigned,
    `nontarget_incorrect_rt_mean` FLOAT,
    `nontarget_incorrect_rt_sd` FLOAT,
    `accuracy` FLOAT,
    `sensitivity`	FLOAT,  
    `specificity`	FLOAT,  
    `results_descript`	VARCHAR(150),  
    `task_file`	VARCHAR(100),  
    `result_file`	VARCHAR(100),
    `browser_name`	VARCHAR(10), 
    `browser_version`	VARCHAR(5), 
    `os_name`	VARCHAR(10), 
    `os_version`	VARCHAR(10), 
    `tablet` 	VARCHAR(10), 
    `mobile`	VARCHAR(10), 
    `screen_resolution`	VARCHAR(12), 
    `window_resolution`	VARCHAR(12), 
    `audio_used`	BOOLEAN, 
    `fullscreen`	BOOLEAN, 
    `online`	BOOLEAN, 
    `use_webaudio_flag` BOOLEAN,
    `touch_mode` BOOLEAN,
    `etc`	VARCHAR(100),  
    PRIMARY KEY(id)
);
        

CREATE TABLE `table_trials` ( 
    `id`	BIGINT unsigned NOT NULL AUTO_INCREMENT, 
    `projectID` CHAR(15),  
    `participantID` CHAR(15),   
    `taskID`	CHAR(15), 
    `taskname`	CHAR(15),
    `session`	TINYINT,   
    `start_time`	DATETIME, 
    `time_elapsed`	INT unsigned,
    `stim_id`   SMALLINT unsigned, 
    `stimulus`	VARCHAR(15), 
    `stim_type`	VARCHAR(5), 
    `stim_subtype`	TINYINT, 
    `stim_duration`	SMALLINT unsigned, 
    `stim_soa`	SMALLINT unsigned,    
    `stim_delay`	SMALLINT unsigned,  
    `states`	VARCHAR(10),    
    `response`	TINYINT, 
    `multi_responses`	VARCHAR(30),
    `rt`	FLOAT(8,1) , 
    `correct_response`	VARCHAR(30),
    `correct`	BOOLEAN,
    `score`	FLOAT, 
    `stim_param1`	FLOAT ,
    `stim_param2`	FLOAT ,
    `stim_param3`	FLOAT ,
    PRIMARY KEY(id)
);
